<a href="https://colab.research.google.com/github/chetankhairnar05/Colab/blob/main/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
l = [1,2,3,4,5]
print(l)
print(type(l))

a = np.array(l)
print(a)
print(type(a))


[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
b = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
print(a.size, a.shape , a.dtype,sep = '   ')
print(b.size, b.shape , b.dtype,sep = '   ')

5   (5,)   int64
10   (2, 5)   int64


In [ ]:
c = np.zeros([2,2],dtype = float)

In [ ]:
c

array([[0., 0.],
       [0., 0.]])

In [ ]:
# d = np.ones([2],dtpe = int)# error
d = np.ones(2,dtype = int)

In [ ]:
d

array([1, 1])

In [ ]:
c = np.ones([3, 3])#default dtpe is float

In [ ]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
array4 = np.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n",
      array4)


Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [16]:
a = np.array([1,2,3,4,5])

In [17]:
print (a)
print(a[1])

[1 2 3 4 5]
2


In [18]:
a[1] = 56
a

array([ 1, 56,  3,  4,  5])

In [19]:
b = a[2:4]
b

array([3, 4])

In [22]:
# a[0, 2] => from matrix a find a[0][2] element it is only possible for 2d matrix of numpy not for 1d array so we need to convert 1d array into 2d matrix to use this
# ex1 => convert into 1*find by itself
arr_1d = np.array([1, 2, 3, 4])
row_vector = arr_1d.reshape(1, -1) # -1 infers the dimension
print(row_vector)
    # Accessing elements using matrix notation
print(row_vector[0, 2]) # Accesses the element at row 0, column 2 (value 3)



[[1 2 3 4]]
3


In [23]:
# ex2: convert into find* 1 matrix
a = np.array([1,2,3,4,5])
b = a.reshape(-1,1)
print(b)
print(b[2,0])

[[1]
 [2]
 [3]
 [4]
 [5]]
3


In [25]:
# a = np.array([1,2],[3,4,5]) # this generates error we need to follow matamatical rules
c = np.array(((1.5, 2, 3), (4, 5, 6)))
print(c)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [27]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[2,3] #we have 0 base indexing
print(a[2,3])

12


In [29]:
from posixpath import sep
# array attributes ndim, shape, size, and dtype
print(a.shape , a.size, a.ndim , a.dtype,sep = '   ')

(3, 4)   12   2   int64


In [30]:
np.zeros(2)# by default float

array([0., 0.])

In [32]:
np.ones(4,dtype = int ) #can specify dtype

array([1, 1, 1, 1])

In [34]:
print(np.empty(4)) #function empty creates an array whose initial content is random
print(np.empty(5,dtype= int))

[1. 1. 1. 1.]
[603365402         0 610693632 615013824        48]


In [36]:
print(np.arange(4))# array form
print(np.arange(2,10,2,dtype = float))#from 2 to 9 with difference 2

[0 1 2 3]
[2. 4. 6. 8.]


In [37]:
np.linspace(0, 10, num=5,dtype = int) #from 0 to 10 total 5 numbers int type(int python like  roundoff)

array([ 0,  2,  5,  7, 10])

In [38]:
np.linspace(0, 10, num=5) # by defau;t float dtype

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [40]:
print(np.linspace(-10, 0, num=5))
print(np.linspace(-10, 0, num=5,dtype = np.int64)) #np has np.float64 np.int64 etc and may other dtypes as well

[-10.   -7.5  -5.   -2.5   0. ]
[-10  -8  -5  -3   0]


In [41]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr)) #return sorted nut do not modify
print(arr)

[1 2 3 4 5 6 7 8]
[2 1 5 3 7 4 6 8]


In [44]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a,b)),a,b,sep = '\n')#use print(np.concatenate((a, b)))  # or [a, b]

[1 2 3 4 5 6 7 8]
[1 2 3 4]
[5 6 7 8]


In [46]:
np.concatenate((a,b),axis = 0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
print(np.concatenate((a,b),axis = 0)) # stack verticaly same number of column
print(np.concatenate((a,b),axis = 1))# stack horizontally same number of rows


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [48]:
# similarly you can make 3d array and then can use ndim , shape , size , dtype

In [52]:
#reshape with a.reshape(a1,b1,c1,.. )or np.reshape(a,  (a1,b1,c1),order='C')
#Yes, if you try to reshape a NumPy array into a shape that doesn't match the total number of elements, it will raise a ValueError.

a = np.arange(6)
print(a)

print()

b = a.reshape(3, 2)
print(b)
print()

print(np.reshape(a, (1, 6), order='C'))# order can be C , A , F default is C

[0 1 2 3 4 5]

[[0 1]
 [2 3]
 [4 5]]

[[0 1 2 3 4 5]]


In [ ]:
#you can index and slice NumPy arrays in the same ways you can slice Python lists.
